apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::643823224298:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1SCA80YG61IP6
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-06-23T20:28:46Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1540"
  uid: 6c9ba3d0-f7a1-47d4-977c-a5ccd0d49ff4